spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: kk23xtk3bb
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        default_schema: public
    hibernate:
      ddl-auto: update
server:
  port: 8085

